# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concurrentActivity <- function(outlen, StartSecond, Duration) {
    .Call(`_ConcurrentActivity_concurrentActivity`, outlen, StartSecond, Duration)
}

concurrentEstimatedThroughput <- function(outlen, StartSecond, Duration, Bytes) {
    .Call(`_ConcurrentActivity_concurrentEstimatedThroughput`, outlen, StartSecond, Duration, Bytes)
}

rcpp_hello_world <- function() {
    .Call(`_ConcurrentActivity_rcpp_hello_world`)
}

